[program:worker-sokrio-staging]
process_name=%(program_name)s_%(process_num)02d
command=php /var/app/current/artisan queue:work redis --sleep=15 --tries=3 --daemon --quiet --queue="default"
autostart=true
autorestart=true
user=root
numprocs=20
redirect_stderr=true
stdout_logfile=/home/sokrio-staging/log/worker.log
stopwaitsecs=3600
